version: 1.0.{build}

image: Visual Studio 2019

install:
  - dotnet tool restore
  - dotnet paket restore
  - cinst pester

build_script:
  - ps: |
      New-Item -ItemType Directory -Name lib
      Copy-Item .\packages\chocolatey.lib\lib\chocolatey.dll .\lib\
      Copy-Item .\packages\log4net\lib\net40-full\log4net.dll .\lib\
      Remove-Item @('.config','.git*','appveyor.yml','.packet*','paket*','packages') -Force -Recurse
      Copy-Item ..\Chocolatier ~\Documents\WindowsPowerShell\Modules -Recurse

test_script:
  - ps: Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.NativeAPI.xml
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.NativeAPI.xml))
  - pwsh: Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.CLI.xml
  - pwsh: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.CLI.xml))

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG_NAME -eq 'current') {Write-Output "Publishing...";Publish-Module -Name Chocolatier -NuGetApiKey "$env:PSGALLERYKEY"}
